MAP_CELL_LENGTH = 64

MAP_MAX_X = MAP_CELL_LENGTH * 128
MAP_MAX_Y = MAP_CELL_LENGTH * 128
MAP_MIN_X = MAP_CELL_LENGTH * (-128)
MAP_MIN_Y = MAP_CELL_LENGTH * (-128)

MAP_WAVE_Y_LENGTH = MAP_CELL_LENGTH * 8
MAP_SPACE_BETWEEN_DEFENDERS_AND_WAVE_Y_LENGTH = MAP_CELL_LENGTH * 16
MAP_DEFENDERS_Y_LENGTH = MAP_CELL_LENGTH * 12
MAP_SPACE_BETWEEN_DEFENDERS_AND_KINK_Y_LENGTH = MAP_CELL_LENGTH * 16
MAP_KINK_Y_LENGTH = MAP_CELL_LENGTH * 12

MAP_SPOT_Y_LENGTH = MAP_WAVE_Y_LENGTH + MAP_SPACE_BETWEEN_DEFENDERS_AND_WAVE_Y_LENGTH + MAP_DEFENDERS_Y_LENGTH + MAP_SPACE_BETWEEN_DEFENDERS_AND_KINK_Y_LENGTH + MAP_KINK_Y_LENGTH
MAP_SPOT_X_LENGTH = MAP_CELL_LENGTH * 32

MAP_SPOT_CENTER_TO_DEFENDER_Y_LENGTH = ( MAP_SPOT_Y_LENGTH / 2 ) - MAP_WAVE_Y_LENGTH - MAP_SPACE_BETWEEN_DEFENDERS_AND_WAVE_Y_LENGTH - (MAP_DEFENDERS_Y_LENGTH / 2)

MAP_Y_BETWEEN_DEFENDER_AND_WAVE = (MAP_WAVE_Y_LENGTH / 2) + MAP_SPACE_BETWEEN_DEFENDERS_AND_WAVE_Y_LENGTH + (MAP_DEFENDERS_Y_LENGTH / 2)

TEAM_GOODGUYS = DOTA_TEAM_GOODGUYS
TEAM_BADGUYS = DOTA_TEAM_BADGUYS
TEAM_CUSTOM_1 = DOTA_TEAM_CUSTOM_1
TEAM_CUSTOM_2 = DOTA_TEAM_CUSTOM_2
TEAM_CUSTOM_3 = DOTA_TEAM_CUSTOM_3
TEAM_CUSTOM_4 = DOTA_TEAM_CUSTOM_4
TEAM_CUSTOM_5 = DOTA_TEAM_CUSTOM_5
TEAM_CUSTOM_6 = DOTA_TEAM_CUSTOM_6
TEAM_CUSTOM_7 = DOTA_TEAM_CUSTOM_7
TEAM_CUSTOM_8 = DOTA_TEAM_CUSTOM_8