MAP_CELL_LENGTH = 64

MAP_MAX_X = MAP_CELL_LENGTH * 128
MAP_MAX_Y = MAP_CELL_LENGTH * 128
MAP_MIN_X = MAP_CELL_LENGTH * (-128)
MAP_MIN_Y = MAP_CELL_LENGTH * (-128)

MAP_WAVE_Y_LENGTH = MAP_CELL_LENGTH * 8
MAP_SPACE_BETWEEN_DEFENDERS_AND_WAVE_Y_LENGTH = MAP_CELL_LENGTH * 16
MAP_DEFENDERS_Y_LENGTH = MAP_CELL_LENGTH * 12
MAP_SPACE_BETWEEN_DEFENDERS_AND_KINK_Y_LENGTH = MAP_CELL_LENGTH * 16
MAP_KINK_Y_LENGTH = MAP_CELL_LENGTH * 12

MAP_SPOT_Y_LENGTH = MAP_WAVE_Y_LENGTH + MAP_SPACE_BETWEEN_DEFENDERS_AND_WAVE_Y_LENGTH + MAP_DEFENDERS_Y_LENGTH + MAP_SPACE_BETWEEN_DEFENDERS_AND_KINK_Y_LENGTH + MAP_KINK_Y_LENGTH
MAP_SPOT_X_LENGTH = MAP_CELL_LENGTH * 32

MAP_SPOT_CENTER_TO_DEFENDER_Y_LENGTH = ( MAP_SPOT_Y_LENGTH / 2 ) - MAP_WAVE_Y_LENGTH - MAP_SPACE_BETWEEN_DEFENDERS_AND_WAVE_Y_LENGTH - (MAP_DEFENDERS_Y_LENGTH / 2)

MAP_Y_BETWEEN_DEFENDER_AND_WAVE = (MAP_WAVE_Y_LENGTH / 2) + MAP_SPACE_BETWEEN_DEFENDERS_AND_WAVE_Y_LENGTH + (MAP_DEFENDERS_Y_LENGTH / 2)