Teams = {}

Teams[1] = DOTA_TEAM_CUSTOM_1
Teams[2] = DOTA_TEAM_CUSTOM_2
Teams[3] = DOTA_TEAM_CUSTOM_3
Teams[4] = DOTA_TEAM_CUSTOM_4
Teams[5] = DOTA_TEAM_CUSTOM_5
Teams[6] = DOTA_TEAM_CUSTOM_6
Teams[7] = DOTA_TEAM_CUSTOM_7
Teams[8] = DOTA_TEAM_CUSTOM_8